### ISSUE TITLE
.deliver_now does not work in Spree 3.0 app

### ISSUE THREAD

**Issue by philbattos** [spree-contrib/spree_mail_settings#15]
I recently upgraded to Spree 3.0 and i discovered that the test emails don't work. When i click the "Send Test Mail" button, i receive this error: Test Mail error: undefined method `deliver_now' for #<Mail::Message:0x007f8e05194278>. When i change the ```.deliver_now``` method to ```.deliver``` in [the mail_methods_controller](https://github.com/spree-contrib/spree_mail_settings/blob/master/app/controllers/spree/admin/mail_methods_controller.rb#L17), it works correctly. 

I see similar behavior in my Spree site when attempting to send a [shipment mailer](https://github.com/spree/spree/blob/master/core/app/models/spree/shipment_handler.rb#L30): the ```.deliver_later``` method throws an error but it works when i change it to ```.deliver```. So this may be an issue that affects Spree on a larger scale. 

I am using Rails 4.2.1. This issue may not be specific to the spree_mail_settings gem but it is affecting my ability to use the gem so i posted it. I've also posted a question in the Spree user group: https://groups.google.com/d/msg/spree-user/Q3-Bw-gsH3w/2f3T1gBPpnUJ

**Comment by philbattos** [comment]
Nevermind, this issue was caused by some custom overrides in my project. Everything is working again.
